config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'users/microposts/:user_id', to: 'microposts#mymicroposts'
  get 'users/comments/:user_id', to: 'comments#mycomments'
  resources :comments
  resources :microposts do
    resources :comments, only: %i[show create update destroy]
  end
  resources :categories
  devise_for :users, controllers: { registrations: 'users/registrations' }
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
  resources :users
  root 'microposts#index'
end

app/models/comment.rb
# frozen_string_literal: true

# app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :micropost, foreign_key: 'micropost_id'
  belongs_to :user
end

app/controllers/comments_controller.rb
# frozen_string_literal: true

# app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_current_user_comments, only: %i[mycomments]
  before_action :set_comment, only: %i[show edit update destroy]

  # GET /comments
  # GET /comments.json
  def index
    @comments = if params[:micropost_id]
                  Comment.where(micropost_id: params[:micropost_id])
                else
                  Comment.all
                end
    @page_title = t('page_title', name: 'Comment')
  end

  # GET /comments/1
  # GET /comments/1.js
  def show
    @page_title = t('page_title', name: 'Comment')
  end

  def mycomments
    @page_title = t('page_title', name: 'My Comments')
  end

  # GET /comments/new
  def new
    @comment = Comment.new
    @page_title = t('page_title', name: 'New Comment')
  end

  # GET /comments/1/edit
  def edit
    @page_title = t('page_title', name: 'Edit Comment')
  end

  # POST /comments
  # POST /comments.json
  def create
    @micropost = Micropost.find(params[:micropost_id])
    @comment = @micropost.comments.new(comment_params)
    @comment.user = current_user
    respond_to do |format|
      if @comment.save
        format.html do
          redirect_to micropost_path(@micropost), notice: t('created', name: 'Comment') # rubocop:disable all
        end
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json do
          render json: @comment.errors, status: :unprocessable_entity
        end
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html do
          redirect_to @comment, notice: t('updated', name: 'Comment')
        end
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json do
          render json: @comment.errors, status: :unprocessable_entity
        end
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @micropost = Micropost.find(params[:micropost_id])
    @comment = @micropost.comments.find(params[:id])
    @comment.destroy
    respond_to do |format|
      format.html do
        redirect_to micropost_path(@micropost),
                    notice: t('destroyed', name: 'Comment')
      end
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_comment
    @comment = Comment.find(params[:id])
  end

  def set_current_user_comments
    @comments = current_user.comments
  end
  # Never trust parameters from the scary internet, only allow the white list through. # rubocop:disable all
  def comment_params
    params.require(:comment).permit(:name, :comment, :micropost_id)
  end
end

app/helpers/comments_helper.rb
# frozen_string_literal: true

# app/helpers/comments_helper.rb
module CommentsHelper
  def show
    'CommentsHelper'
  end
end

app/views/comments/_form.html.slim
= form_with(model:[micropost, Comment.new], local:true) do |form|
  .field
    = form.label :name
    = form.text_field :name
  .field
    = form.label :comment
    = form.text_area :comment
  .actions
    = form.submit

app/views/comments/edit.html.slim
= render 'form', comment: @comment
= link_to 'Show', @comment
|  |
= link_to 'Back', comments_path

app/views/comments/index.html.slim
p#notice
  = notice
h1
  | Comments
table
  thead
    tr
      th
        | Name
      th
        | Comment
      th[colspan="2"]
  tbody
    - @comments.each do |comment|
      tr
        td
          = comment.name
        td
          = comment.comment
        td
          = link_to 'Show', comment
        - if user_signed_in? && comment.user_id == current_user.id
          td
            = link_to 'Destroy', [comment.micropost, comment], method: :delete, data: { confirm: 'Are you sure?' }
br
= link_to 'New Comment', new_comment_path
| |
= link_to 'Micropost', microposts_path

app/views/comments/mycomments.html.slim
p#notice
  = notice
table
  thead
    tr
      th
        | Name
      th
        | Comment
      th[colspan="2"]
  tbody
    - @comments.each do |comment|
      tr
        td
          = comment.name
        td
          = comment.comment
        td
          = link_to 'Show', comment
        - if user_signed_in? && comment.user_id == current_user.id
          td
            = link_to 'Destroy', [comment.micropost, comment], method: :delete, data: { confirm: 'Are you sure?' }
br
= link_to 'New Comment', new_comment_path
| |
= link_to 'Micropost', microposts_path

app/views/comments/new.html.slim
= render 'form', comment: @comment
= link_to 'Back', comments_path

app/views/comments/show.html.slim
p#notice
  = notice
p
  strong
    | Name:
  = @comment.name
p
  strong
    | Comment:
  = @comment.comment
= link_to 'Back', comments_path