config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'users/microposts/:user_id', to: 'microposts#mymicroposts'
  get 'users/comments/:user_id', to: 'comments#mycomments'
  resources :comments
  resources :microposts do
    resources :comments, only: %i[show create update destroy]
  end
  resources :categories
  devise_for :users, controllers: { registrations: 'users/registrations' }
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
  resources :users
  root 'microposts#index'
end

app/models/micropost.rb
# frozen_string_literal: true

# app/models/micropost.rb
class Micropost < ApplicationRecord
  belongs_to :user, foreign_key: 'user_id'
  delegate :name, to: :user, prefix: true
  has_many :category_microposts, dependent: :destroy
  has_many :categories, through: :category_microposts
  has_many :comments, dependent: :destroy
  has_one_attached :image
  validates :content, presence: true, length: { maximum: 140 }
  paginates_per 10
end

app/controllers/microposts_controller.rb
# frozen_string_literal: true

# app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  before_action :set_current_user_micropost, only: %i[edit update destroy]
  before_action :set_current_user_microposts, only: %i[mymicroposts]
  before_action :set_micropost, only: %i[show]

  # GET /microposts
  # GET /microposts.json
  def index
    @q = Micropost.ransack(params[:q])
    @microposts = @q.result(distinct: true).page(params[:page]).order('created_at DESC')
    @page_title = t('page_title', name: 'Micropost')
  end

  # GET /microposts/1
  # GET /microposts/1.json
  def show
    @page_title = t('page_title', name: 'Micropost')
  end

  def mymicroposts
    @page_title = t('page_title', name: 'My Microposts')
  end

  # GET /microposts/new
  def new
    @micropost = Micropost.new
    @page_title = t('page_title', name: 'New Micropost')
  end

  # GET /microposts/1/edit
  def edit
    @page_title = t('page_title', name: 'Edit Micropost')
  end

  # POST /microposts
  # POST /microposts.json
  def create
    @micropost = current_user.microposts.new(micropost_params)
    respond_to do |format|
      if @micropost.save
        format.html do
          redirect_to @micropost, notice: t('created', name: 'Micropost')
        end
        format.json { render :show, status: :created, location: @micropost }
      else
        format.html { render :new }
        format.json do
          render json: @micropost.errors,
                 status: :unprocessable_entity
        end
      end
    end
  end

  # PATCH/PUT /microposts/1
  # PATCH/PUT /microposts/1.json
  def update
    respond_to do |format|
      if @micropost.update(micropost_params)
        format.html do
          redirect_to @micropost, notice: t('updated', name: 'Micropost')
        end
        format.json { render :show, status: :ok, location: @micropost }
      else
        format.html { render :edit }
        format.json do
          render json: @micropost.errors,
                 status: :unprocessable_entity
        end
      end
    end
  end

  # DELETE /microposts/1
  # DELETE /microposts/1.json
  def destroy
    if @micropost == set_micropost
      Comment.where(micropost_id: @micropost.id).destroy_all
      @micropost.destroy
    end
    respond_to do |format|
      format.html do
        redirect_to microposts_url, notice: t('destroyed', name: 'Micropost')
      end
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_micropost
    @micropost = Micropost.find(params[:id])
  end

  def set_current_user_micropost
    @micropost = current_user.microposts.find(params[:id])
  end

  def set_current_user_microposts
    @microposts = current_user.microposts
  end
  # Never trust parameters from the scary internet, only allow the white list through. # rubocop:disable all
  def micropost_params
    params.require(:micropost).permit(:content, :image, category_ids: [])
  end
end

app/helpers/microposts_helper.rb
# frozen_string_literal: true

# app/helpers/microposts_helper.rb
module MicropostsHelper
  def show
    'MicropostsHelper'
  end
end

app/views/microposts/_form.html.slim
= form_with(model: micropost, local: true) do |form|
  - if micropost.errors.any?
    #error_explanation
      h2
        = pluralize(micropost.errors.count, "error")
        |  prohibited this micropost from being saved:
      ul
        - micropost.errors.full_messages.each do |message|
          li
            = message
  .field
    - Category.all.each do |cat|
      = check_box_tag "micropost[category_ids][]", cat.id, form.object.categories.include?(cat)
      = cat.name
  = link_to 'New Categories', categories_path
  br
  .field
    = form.label :content
    = form.text_area :content
  .field
    = form.label :image
    = form.file_field :image
  .actions
    = form.submit

app/views/microposts/edit.html.slim
= render 'form', micropost: @micropost
= link_to 'Show', @micropost
|  |
= link_to 'Back', microposts_path

app/views/microposts/index.html.slim
p#notice
  = notice
h1
  | Microposts
table
  thead
    tr
      th
        | Category:
      th
        | User:
      th
        | Content:
      th colspan="3"
  tbody
    - @microposts.each do |micropost|
      tr
        td
          - micropost.categories.each do |category|
            li
              = link_to category.name, category_path(category)
        td
          = micropost.user_name
        td
          = micropost.content
        td
          = link_to 'Show', micropost
        td
          - if user_signed_in? && micropost.user_id == current_user.id
            = link_to 'Edit', edit_micropost_path(micropost)
        td
          - if user_signed_in? && micropost.user_id == current_user.id
            = link_to 'Delete', micropost, method: :delete, data: { confirm: 'Are you sure?' }
br
= link_to 'New Micropost', new_micropost_path

app/views/microposts/mymicroposts.html.slim
p#notice
  = notice
table
  thead
    tr
      th
        | Category:
      th
        | User:
      th
        | Content:
      th colspan="3"
  tbody
    - @microposts.each do |micropost|
      tr
        td
          - micropost.categories.each do |category|
            li
              = link_to category.name, category_path(category)
        td
          = micropost.user_name
        td
          = micropost.content
        td
          = link_to 'Show', micropost
        td
          - if user_signed_in? && micropost.user_id == current_user.id
            = link_to 'Edit', edit_micropost_path(micropost)
        td
          - if user_signed_in? && micropost.user_id == current_user.id
            = link_to 'Delete', micropost, method: :delete, data: { confirm: 'Are you sure?' }
br
= link_to 'New Micropost', new_micropost_path

app/views/microposts/new.html.slim
= render 'form', micropost: @micropost
= link_to 'Back', microposts_path

app/views/microposts/show.html.erb
<div id="micropost" data-id="<%= @micropost.id %>" data-user="<%= @micropost.user_id %>">
  <div id="user" data-id="<%= current_user.id %>">
    <p id="notice"><%= notice %></p>

    <% if @micropost.image.attached? %>
      <p>
        <strong> Image: </strong>
        <%= image_tag @micropost.image %>
      </p>
    <% end %>

    <p>
      <strong>Content:</strong>
      <%= @micropost.content %>
    </p>

    <p>
      <strong>Category:</strong>
      <% @micropost.categories.each do |category|%>
        <li><%= link_to category.name, category_path(category)%></li>
      <% end %>
    </p>

    <p>
      <strong>User:</strong>
      <%= @micropost.user_name %>
    </p>

    <table id="comments">
      <thead>
        <tr>
          <th>Name</th>
          <th>Comment</th>
        </tr>
      </thead>
    </table>

    </br>
    <%= render partial:'comments/form', locals: {micropost: @micropost} %>

    <% if user_signed_in? && @micropost.user_id == current_user.id %>
      <%= link_to 'Edit', edit_micropost_path(@micropost) %>
      |
    <% end %>
    <%= link_to 'Back', microposts_path %>
  </div>
</div>

<script>
$(function() {
  var url = '/comments.json?micropost_id=' + $('#micropost').data('id')
  $.get(url, function(result) {
    result.forEach(function(comment) {
      var tr = $('<tr>')
      tr.html("<td>"+comment.name+"</td>"
            + "<td>"+comment.comment+"</td>")
      if ($('#micropost').data('user') == $('#user').data('id')) {
        tr.append(`<a href='/comments/${comment.id}?micropost_id=${comment.micropost_id}' data-method="delete">Delete</a>`)
      }
      $('#comments').append(tr)
    })
  })
})
</script>