config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'users/microposts/:user_id', to: 'microposts#mymicroposts'
  get 'users/comments/:user_id', to: 'comments#mycomments'
  resources :comments
  resources :microposts do
    resources :comments, only: %i[show create update destroy]
  end
  resources :categories
  devise_for :users, controllers: { registrations: 'users/registrations' }
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
  resources :users
  root 'microposts#index'
end

app/models/category.rb
# frozen_string_literal: true

# app/models/category.rb
class Category < ApplicationRecord
  has_many :category_microposts, dependent: :destroy
  has_many :microposts, through: :category_microposts
end

app/controllers/categories_controller.rb
# frozen_string_literal: true

# app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[show edit update destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show; end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit; end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)
    respond_to do |format|
      if @category.save
        format.html do
          redirect_to @category, notice: t('created', name: 'Category')
        end
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json do
          render json: @category.errors, status: :unprocessable_entity
        end
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html do
          redirect_to @category, notice: t('updated', name: 'Category')
        end
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json do
          render json: @category.errors,
                 status: :unprocessable_entity
        end
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html do
        redirect_to categories_url, notice: t('destroyed', name: 'Category')
      end
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_category
    @category = Category.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.  # rubocop:disable all
  def category_params
    params.require(:category).permit(:name)
  end
end

app/helpers/categories_helper.rb
# frozen_string_literal: true

# app/helpers/categories_helper.rb
module CategoriesHelper
  def show
    'CategoriesHelper'
  end
end

app/views/categories/_form.html.slim
= form_with(model: category, local: true) do |form|
  - if category.errors.any?
    #error_explanation
      h2
        = pluralize(category.errors.count, "error")
        |  prohibited this category from being saved:
      ul
        - category.errors.full_messages.each do |message|
          li
            = message
  .field
    = form.label :name
    = form.text_field :name
  .actions
    = form.submit

app/views/categories/edit.html.slim
h1
  | Editing Category
= render 'form', category: @category
= link_to 'Show', @category
|  |
= link_to 'Back', categories_path

app/views/categories/index.html.slim
p#notice
  = notice
h1
  | Categories
table
  thead
    tr
      th
        | Name
      th
        | Count
      th[colspan="3"]
  tbody
    - @categories.order(name: :asc).each do |category|
      tr
        td
          = category.name
        td
          = category.microposts_count
        td
          = link_to 'Show', category
        td
          = link_to 'Edit', edit_category_path(category)
        td
          = link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' }
br
= link_to 'New Category', new_category_path
| |
= link_to 'Microposts', microposts_path

app/views/categories/new.html.slim
h1
  | New Category
= render 'form', category: @category
= link_to 'Back', categories_path

app/views/categories/show.html.slim
p#notice
  = notice
p
  strong
    | name
  = @category.name

table
  thead
    tr
      th
        | User
      th
        | Micropost
  tbody
    - @category.microposts.each do |micropost|
      tr
        td
          = micropost.user_name
        td
          = micropost.content

= link_to 'Edit', edit_category_path(@category)
|  |
= link_to 'Back to Categories', categories_path
|  |
= link_to 'Back to Microposts', microposts_path